name: app
description: "GluCoCare"
publish_to: 'none'

version: 1.0.1+12

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  # 데이터직렬화
  json_annotation: ^4.9.0
  # 상태관리
  flutter_riverpod: ^2.6.1
  # 내부저장소
  shared_preferences: ^2.5.2
  flutter_secure_storage: ^9.2.4
  # 화면 내 알림
  another_flushbar: ^1.12.30
  # HTTP 요청 처리
  dio: ^5.8.0+1
  # 차트 그리기
  fl_chart: ^1.0.0
  syncfusion_flutter_charts: ^30.1.42
  intl: ^0.20.2
  # 파이어베이스
  firebase_core: ^4.0.0
  firebase_messaging: ^16.0.0
  # 알림 
  flutter_local_notifications: ^19.4.0
  # 권한 관리
  permission_handler: ^12.0.1
  # 건강활동데이터
  health: ^13.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  # 데이터직렬화
  json_serializable: ^6.9.4
  build_runner: ^2.4.15 # dart run build_runner build

flutter:

  uses-material-design: true

  assets:
    - assets/logo/
